// hcal_tree: base class to handle reduced tree ntuples
// File generated with generate_hcal_tree.exe

#ifndef H_hcal_tree
#define H_hcal_tree

#include <vector>
#include <string>

#include "TTree.h"
#include "TChain.h"
#include "TTreeFormula.h"

class hcal_tree{
public:
  hcal_tree(); // Constructor to create tree
  hcal_tree(const std::string &filename); // Constructor to read tree

  int Add(const std::string &filename);
  long GetEntries() const;
  virtual void GetEntry(const long entry);
  float GetBranchValue(TString branch);
  bool PassString(TString cut);

  virtual void Fill();
  void Write();

  virtual std::string Type() const;

  static const double bad_val_;

  virtual ~hcal_tree();

  int  const & bx() const;
  int  & bx();
  int  const & event() const;
  int  & event();
  int  const & ls() const;
  int  & ls();
  int  const & run() const;
  int  & run();
  std::vector<bool>  const & HLTInsideDatasetTriggerDecisions() const;
  std::vector<bool>  & HLTInsideDatasetTriggerDecisions();
  std::vector<bool>  const & HLTOutsideDatasetTriggerDecisions() const;
  std::vector<bool>  & HLTOutsideDatasetTriggerDecisions();
  std::vector<double>  const & EBET() const;
  std::vector<double>  & EBET();
  std::vector<double>  const & EBSumE() const;
  std::vector<double>  & EBSumE();
  std::vector<double>  const & EBSumET() const;
  std::vector<double>  & EBSumET();
  std::vector<double>  const & EEET() const;
  std::vector<double>  & EEET();
  std::vector<double>  const & EESumE() const;
  std::vector<double>  & EESumE();
  std::vector<double>  const & EESumET() const;
  std::vector<double>  & EESumET();
  std::vector<double>  const & HBET() const;
  std::vector<double>  & HBET();
  std::vector<double>  const & HBHERecHitEnergyAux() const;
  std::vector<double>  & HBHERecHitEnergyAux();
  std::vector<double>  const & HBHERecHitEnergyRaw() const;
  std::vector<double>  & HBHERecHitEnergyRaw();
  std::vector<double>  const & HBSumE() const;
  std::vector<double>  & HBSumE();
  std::vector<double>  const & HBSumET() const;
  std::vector<double>  & HBSumET();
  std::vector<double>  const & HEET() const;
  std::vector<double>  & HEET();
  std::vector<double>  const & HESumE() const;
  std::vector<double>  & HESumE();
  std::vector<double>  const & HESumET() const;
  std::vector<double>  & HESumET();
  std::vector<double>  const & HFET() const;
  std::vector<double>  & HFET();
  std::vector<double>  const & HFPhase1RecHitEta() const;
  std::vector<double>  & HFPhase1RecHitEta();
  std::vector<double>  const & HFPhase1RecHitPhi() const;
  std::vector<double>  & HFPhase1RecHitPhi();
  std::vector<double>  const & IsolatedNoiseSumE() const;
  std::vector<double>  & IsolatedNoiseSumE();
  std::vector<double>  const & IsolatedNoiseSumEt() const;
  std::vector<double>  & IsolatedNoiseSumEt();
  std::vector<double>  const & JetEMEB() const;
  std::vector<double>  & JetEMEB();
  std::vector<double>  const & JetEMEE() const;
  std::vector<double>  & JetEMEE();
  std::vector<double>  const & JetEMFrac() const;
  std::vector<double>  & JetEMFrac();
  std::vector<double>  const & JetEMHF() const;
  std::vector<double>  & JetEMHF();
  std::vector<double>  const & JetEta() const;
  std::vector<double>  & JetEta();
  std::vector<double>  const & JetHadFrac() const;
  std::vector<double>  & JetHadFrac();
  std::vector<double>  const & JetHadHB() const;
  std::vector<double>  & JetHadHB();
  std::vector<double>  const & JetHadHE() const;
  std::vector<double>  & JetHadHE();
  std::vector<double>  const & JetHadHF() const;
  std::vector<double>  & JetHadHF();
  std::vector<double>  const & JetPhi() const;
  std::vector<double>  & JetPhi();
  std::vector<double>  const & JetPt() const;
  std::vector<double>  & JetPt();
  std::vector<double>  const & MaxE2E10() const;
  std::vector<double>  & MaxE2E10();
  std::vector<double>  const & MinE2E10() const;
  std::vector<double>  & MinE2E10();
  std::vector<double>  const & MuonCalEnergyEm() const;
  std::vector<double>  & MuonCalEnergyEm();
  std::vector<double>  const & MuonCalEnergyEmS25() const;
  std::vector<double>  & MuonCalEnergyEmS25();
  std::vector<double>  const & MuonCalEnergyHad() const;
  std::vector<double>  & MuonCalEnergyHad();
  std::vector<double>  const & MuonCalEnergyHadS9() const;
  std::vector<double>  & MuonCalEnergyHadS9();
  std::vector<double>  const & MuonEta() const;
  std::vector<double>  & MuonEta();
  std::vector<double>  const & MuonPhi() const;
  std::vector<double>  & MuonPhi();
  std::vector<double>  const & MuonPt() const;
  std::vector<double>  & MuonPt();
  std::vector<double>  const & NegativeNoiseSumE() const;
  std::vector<double>  & NegativeNoiseSumE();
  std::vector<double>  const & NegativeNoiseSumEt() const;
  std::vector<double>  & NegativeNoiseSumEt();
  std::vector<double>  const & NominalMET() const;
  std::vector<double>  & NominalMET();
  std::vector<double>  const & RBXEnergy() const;
  std::vector<double>  & RBXEnergy();
  std::vector<double>  const & RBXEnergy15() const;
  std::vector<double>  & RBXEnergy15();
  std::vector<double>  const & SpikeNoiseSumE() const;
  std::vector<double>  & SpikeNoiseSumE();
  std::vector<double>  const & SpikeNoiseSumEt() const;
  std::vector<double>  & SpikeNoiseSumEt();
  std::vector<float>  const & HBHERecHitEnergy() const;
  std::vector<float>  & HBHERecHitEnergy();
  std::vector<float>  const & HBHERecHitEta() const;
  std::vector<float>  & HBHERecHitEta();
  std::vector<float>  const & HBHERecHitPhi() const;
  std::vector<float>  & HBHERecHitPhi();
  std::vector<float>  const & HBHERecHitTime() const;
  std::vector<float>  & HBHERecHitTime();
  std::vector<float>  const & HFRecHitEnergy() const;
  std::vector<float>  & HFRecHitEnergy();
  std::vector<float>  const & HFRecHitEta() const;
  std::vector<float>  & HFRecHitEta();
  std::vector<float>  const & HFRecHitPhi() const;
  std::vector<float>  & HFRecHitPhi();
  std::vector<float>  const & HFRecHitTime() const;
  std::vector<float>  & HFRecHitTime();
  std::vector<int>  const & HBHEDigiDepth() const;
  std::vector<int>  & HBHEDigiDepth();
  std::vector<int>  const & HBHEDigiIEta() const;
  std::vector<int>  & HBHEDigiIEta();
  std::vector<int>  const & HBHEDigiIPhi() const;
  std::vector<int>  & HBHEDigiIPhi();
  std::vector<int>  const & HBHERecHitAux() const;
  std::vector<int>  & HBHERecHitAux();
  std::vector<int>  const & HBHERecHitDepth() const;
  std::vector<int>  & HBHERecHitDepth();
  std::vector<int>  const & HBHERecHitFlags() const;
  std::vector<int>  & HBHERecHitFlags();
  std::vector<int>  const & HBHERecHitHPDid() const;
  std::vector<int>  & HBHERecHitHPDid();
  std::vector<int>  const & HBHERecHitIEta() const;
  std::vector<int>  & HBHERecHitIEta();
  std::vector<int>  const & HBHERecHitIPhi() const;
  std::vector<int>  & HBHERecHitIPhi();
  std::vector<int>  const & HBHERecHitRBXid() const;
  std::vector<int>  & HBHERecHitRBXid();
  std::vector<int>  const & HBHERecHitSevLvl() const;
  std::vector<int>  & HBHERecHitSevLvl();
  std::vector<int>  const & HFPhase1RecHitDepth() const;
  std::vector<int>  & HFPhase1RecHitDepth();
  std::vector<int>  const & HFPhase1RecHitIEta() const;
  std::vector<int>  & HFPhase1RecHitIEta();
  std::vector<int>  const & HFPhase1RecHitIPhi() const;
  std::vector<int>  & HFPhase1RecHitIPhi();
  std::vector<int>  const & HFRecHitAux() const;
  std::vector<int>  & HFRecHitAux();
  std::vector<int>  const & HFRecHitDepth() const;
  std::vector<int>  & HFRecHitDepth();
  std::vector<int>  const & HFRecHitFlags() const;
  std::vector<int>  & HFRecHitFlags();
  std::vector<int>  const & HFRecHitHPDid() const;
  std::vector<int>  & HFRecHitHPDid();
  std::vector<int>  const & HFRecHitIEta() const;
  std::vector<int>  & HFRecHitIEta();
  std::vector<int>  const & HFRecHitIPhi() const;
  std::vector<int>  & HFRecHitIPhi();
  std::vector<int>  const & HFRecHitRBXid() const;
  std::vector<int>  & HFRecHitRBXid();
  std::vector<int>  const & HLTBits() const;
  std::vector<int>  & HLTBits();
  std::vector<int>  const & HLTInsideDatasetTriggerPrescales() const;
  std::vector<int>  & HLTInsideDatasetTriggerPrescales();
  std::vector<int>  const & HLTOutsideDatasetTriggerPrescales() const;
  std::vector<int>  & HLTOutsideDatasetTriggerPrescales();
  std::vector<int>  const & HPDHits() const;
  std::vector<int>  & HPDHits();
  std::vector<int>  const & HPDNoOtherHits() const;
  std::vector<int>  & HPDNoOtherHits();
  std::vector<int>  const & HasBadRBXR45() const;
  std::vector<int>  & HasBadRBXR45();
  std::vector<int>  const & HasBadRBXRechitR45Loose() const;
  std::vector<int>  & HasBadRBXRechitR45Loose();
  std::vector<int>  const & HasBadRBXRechitR45Tight() const;
  std::vector<int>  & HasBadRBXRechitR45Tight();
  std::vector<int>  const & IsoNoiseFilterDecision() const;
  std::vector<int>  & IsoNoiseFilterDecision();
  std::vector<int>  const & JetN60() const;
  std::vector<int>  & JetN60();
  std::vector<int>  const & JetN90() const;
  std::vector<int>  & JetN90();
  std::vector<int>  const & MaxZeros() const;
  std::vector<int>  & MaxZeros();
  std::vector<int>  const & MuonCSC2DRecHitsSize() const;
  std::vector<int>  & MuonCSC2DRecHitsSize();
  std::vector<int>  const & MuonCSCSegmentsSize() const;
  std::vector<int>  & MuonCSCSegmentsSize();
  std::vector<int>  const & MuonDT1DCosmicRecHitsSize() const;
  std::vector<int>  & MuonDT1DCosmicRecHitsSize();
  std::vector<int>  const & MuonDT1DRecHitsSize() const;
  std::vector<int>  & MuonDT1DRecHitsSize();
  std::vector<int>  const & MuonDTRecCosmicSegmentsSize() const;
  std::vector<int>  & MuonDTRecCosmicSegmentsSize();
  std::vector<int>  const & MuonDTRecSegmentsSize() const;
  std::vector<int>  & MuonDTRecSegmentsSize();
  std::vector<int>  const & MuonNumberOfChambers() const;
  std::vector<int>  & MuonNumberOfChambers();
  std::vector<int>  const & MuonNumberOfMatchedRPCLayers() const;
  std::vector<int>  & MuonNumberOfMatchedRPCLayers();
  std::vector<int>  const & MuonNumberOfMatchedStations() const;
  std::vector<int>  & MuonNumberOfMatchedStations();
  std::vector<int>  const & MuonRPCRecHitsSize() const;
  std::vector<int>  & MuonRPCRecHitsSize();
  std::vector<int>  const & NumIsolatedNoiseChannels() const;
  std::vector<int>  & NumIsolatedNoiseChannels();
  std::vector<int>  const & NumNegativeNoiseChannels() const;
  std::vector<int>  & NumNegativeNoiseChannels();
  std::vector<int>  const & NumSpikeNoiseChannels() const;
  std::vector<int>  & NumSpikeNoiseChannels();
  std::vector<int>  const & Nvtx() const;
  std::vector<int>  & Nvtx();
  std::vector<int>  const & OfficialDecision() const;
  std::vector<int>  & OfficialDecision();
  std::vector<int>  const & OfficialDecisionRun1() const;
  std::vector<int>  & OfficialDecisionRun1();
  std::vector<int>  const & OfficialDecisionRun2L() const;
  std::vector<int>  & OfficialDecisionRun2L();
  std::vector<int>  const & OfficialDecisionRun2T() const;
  std::vector<int>  & OfficialDecisionRun2T();
  std::vector<int>  const & QIE10DigiDepth() const;
  std::vector<int>  & QIE10DigiDepth();
  std::vector<int>  const & QIE10DigiIEta() const;
  std::vector<int>  & QIE10DigiIEta();
  std::vector<int>  const & QIE10DigiIPhi() const;
  std::vector<int>  & QIE10DigiIPhi();
  std::vector<int>  const & QIE11DigiDepth() const;
  std::vector<int>  & QIE11DigiDepth();
  std::vector<int>  const & QIE11DigiIEta() const;
  std::vector<int>  & QIE11DigiIEta();
  std::vector<int>  const & QIE11DigiIPhi() const;
  std::vector<int>  & QIE11DigiIPhi();
  std::vector<std::string>  const & HLTInsideDatasetTriggerNames() const;
  std::vector<std::string>  & HLTInsideDatasetTriggerNames();
  std::vector<std::string>  const & HLTOutsideDatasetTriggerNames() const;
  std::vector<std::string>  & HLTOutsideDatasetTriggerNames();
  std::vector<std::vector<double> >  const & HBHERecHitAuxAllfC() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxAllfC();
  std::vector<std::vector<double> >  const & HBHERecHitAuxEnergy() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxEnergy();
  std::vector<std::vector<double> >  const & HBHERecHitAuxFC() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxFC();
  std::vector<std::vector<double> >  const & HBHERecHitAuxGain() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxGain();
  std::vector<std::vector<double> >  const & HBHERecHitAuxPedFC() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxPedFC();
  std::vector<std::vector<double> >  const & HBHERecHitAuxRCGain() const;
  std::vector<std::vector<double> >  & HBHERecHitAuxRCGain();
  std::vector<std::vector<double> >  const & QIE10DigiFC() const;
  std::vector<std::vector<double> >  & QIE10DigiFC();
  std::vector<std::vector<double> >  const & QIE11DigiFC() const;
  std::vector<std::vector<double> >  & QIE11DigiFC();
  std::vector<std::vector<double> >  const & RBXCharge() const;
  std::vector<std::vector<double> >  & RBXCharge();
  std::vector<std::vector<double> >  const & RBXCharge15() const;
  std::vector<std::vector<double> >  & RBXCharge15();
  std::vector<std::vector<float> >  const & HBHEDigiAllFC() const;
  std::vector<std::vector<float> >  & HBHEDigiAllFC();
  std::vector<std::vector<float> >  const & HFPhase1RecHitQie10Charge() const;
  std::vector<std::vector<float> >  & HFPhase1RecHitQie10Charge();
  std::vector<std::vector<float> >  const & HFPhase1RecHitQie10Energy() const;
  std::vector<std::vector<float> >  & HFPhase1RecHitQie10Energy();
  std::vector<std::vector<float> >  const & HFPhase1RecHitQie10Time() const;
  std::vector<std::vector<float> >  & HFPhase1RecHitQie10Time();
  std::vector<std::vector<int> >  const & HBHERecHitAuxADC() const;
  std::vector<std::vector<int> >  & HBHERecHitAuxADC();
  std::vector<std::vector<int> >  const & HBHERecHitAuxCapID() const;
  std::vector<std::vector<int> >  & HBHERecHitAuxCapID();
  std::vector<std::vector<int> >  const & L1PhysBits() const;
  std::vector<std::vector<int> >  & L1PhysBits();
  std::vector<std::vector<int> >  const & L1TechBits() const;
  std::vector<std::vector<int> >  & L1TechBits();
  std::vector<std::vector<int> >  const & QIE10DigiLETDC() const;
  std::vector<std::vector<int> >  & QIE10DigiLETDC();


protected:
  TChain chain_;
  TTree tree_;
  long entry_;
  const bool read_only_;

private:
  class VectorLoader{
  public:
    VectorLoader();
  private:
    static bool loaded_;
  };

  static VectorLoader vl_;
  int  bx_;
  TBranch *b_bx_;
  mutable bool c_bx_;
  int  event_;
  TBranch *b_event_;
  mutable bool c_event_;
  int  ls_;
  TBranch *b_ls_;
  mutable bool c_ls_;
  int  run_;
  TBranch *b_run_;
  mutable bool c_run_;
  std::vector<bool>  HLTInsideDatasetTriggerDecisions_;
  std::vector<bool>  *p_HLTInsideDatasetTriggerDecisions_;
  TBranch *b_HLTInsideDatasetTriggerDecisions_;
  mutable bool c_HLTInsideDatasetTriggerDecisions_;
  std::vector<bool>  HLTOutsideDatasetTriggerDecisions_;
  std::vector<bool>  *p_HLTOutsideDatasetTriggerDecisions_;
  TBranch *b_HLTOutsideDatasetTriggerDecisions_;
  mutable bool c_HLTOutsideDatasetTriggerDecisions_;
  std::vector<double>  EBET_;
  std::vector<double>  *p_EBET_;
  TBranch *b_EBET_;
  mutable bool c_EBET_;
  std::vector<double>  EBSumE_;
  std::vector<double>  *p_EBSumE_;
  TBranch *b_EBSumE_;
  mutable bool c_EBSumE_;
  std::vector<double>  EBSumET_;
  std::vector<double>  *p_EBSumET_;
  TBranch *b_EBSumET_;
  mutable bool c_EBSumET_;
  std::vector<double>  EEET_;
  std::vector<double>  *p_EEET_;
  TBranch *b_EEET_;
  mutable bool c_EEET_;
  std::vector<double>  EESumE_;
  std::vector<double>  *p_EESumE_;
  TBranch *b_EESumE_;
  mutable bool c_EESumE_;
  std::vector<double>  EESumET_;
  std::vector<double>  *p_EESumET_;
  TBranch *b_EESumET_;
  mutable bool c_EESumET_;
  std::vector<double>  HBET_;
  std::vector<double>  *p_HBET_;
  TBranch *b_HBET_;
  mutable bool c_HBET_;
  std::vector<double>  HBHERecHitEnergyAux_;
  std::vector<double>  *p_HBHERecHitEnergyAux_;
  TBranch *b_HBHERecHitEnergyAux_;
  mutable bool c_HBHERecHitEnergyAux_;
  std::vector<double>  HBHERecHitEnergyRaw_;
  std::vector<double>  *p_HBHERecHitEnergyRaw_;
  TBranch *b_HBHERecHitEnergyRaw_;
  mutable bool c_HBHERecHitEnergyRaw_;
  std::vector<double>  HBSumE_;
  std::vector<double>  *p_HBSumE_;
  TBranch *b_HBSumE_;
  mutable bool c_HBSumE_;
  std::vector<double>  HBSumET_;
  std::vector<double>  *p_HBSumET_;
  TBranch *b_HBSumET_;
  mutable bool c_HBSumET_;
  std::vector<double>  HEET_;
  std::vector<double>  *p_HEET_;
  TBranch *b_HEET_;
  mutable bool c_HEET_;
  std::vector<double>  HESumE_;
  std::vector<double>  *p_HESumE_;
  TBranch *b_HESumE_;
  mutable bool c_HESumE_;
  std::vector<double>  HESumET_;
  std::vector<double>  *p_HESumET_;
  TBranch *b_HESumET_;
  mutable bool c_HESumET_;
  std::vector<double>  HFET_;
  std::vector<double>  *p_HFET_;
  TBranch *b_HFET_;
  mutable bool c_HFET_;
  std::vector<double>  HFPhase1RecHitEta_;
  std::vector<double>  *p_HFPhase1RecHitEta_;
  TBranch *b_HFPhase1RecHitEta_;
  mutable bool c_HFPhase1RecHitEta_;
  std::vector<double>  HFPhase1RecHitPhi_;
  std::vector<double>  *p_HFPhase1RecHitPhi_;
  TBranch *b_HFPhase1RecHitPhi_;
  mutable bool c_HFPhase1RecHitPhi_;
  std::vector<double>  IsolatedNoiseSumE_;
  std::vector<double>  *p_IsolatedNoiseSumE_;
  TBranch *b_IsolatedNoiseSumE_;
  mutable bool c_IsolatedNoiseSumE_;
  std::vector<double>  IsolatedNoiseSumEt_;
  std::vector<double>  *p_IsolatedNoiseSumEt_;
  TBranch *b_IsolatedNoiseSumEt_;
  mutable bool c_IsolatedNoiseSumEt_;
  std::vector<double>  JetEMEB_;
  std::vector<double>  *p_JetEMEB_;
  TBranch *b_JetEMEB_;
  mutable bool c_JetEMEB_;
  std::vector<double>  JetEMEE_;
  std::vector<double>  *p_JetEMEE_;
  TBranch *b_JetEMEE_;
  mutable bool c_JetEMEE_;
  std::vector<double>  JetEMFrac_;
  std::vector<double>  *p_JetEMFrac_;
  TBranch *b_JetEMFrac_;
  mutable bool c_JetEMFrac_;
  std::vector<double>  JetEMHF_;
  std::vector<double>  *p_JetEMHF_;
  TBranch *b_JetEMHF_;
  mutable bool c_JetEMHF_;
  std::vector<double>  JetEta_;
  std::vector<double>  *p_JetEta_;
  TBranch *b_JetEta_;
  mutable bool c_JetEta_;
  std::vector<double>  JetHadFrac_;
  std::vector<double>  *p_JetHadFrac_;
  TBranch *b_JetHadFrac_;
  mutable bool c_JetHadFrac_;
  std::vector<double>  JetHadHB_;
  std::vector<double>  *p_JetHadHB_;
  TBranch *b_JetHadHB_;
  mutable bool c_JetHadHB_;
  std::vector<double>  JetHadHE_;
  std::vector<double>  *p_JetHadHE_;
  TBranch *b_JetHadHE_;
  mutable bool c_JetHadHE_;
  std::vector<double>  JetHadHF_;
  std::vector<double>  *p_JetHadHF_;
  TBranch *b_JetHadHF_;
  mutable bool c_JetHadHF_;
  std::vector<double>  JetPhi_;
  std::vector<double>  *p_JetPhi_;
  TBranch *b_JetPhi_;
  mutable bool c_JetPhi_;
  std::vector<double>  JetPt_;
  std::vector<double>  *p_JetPt_;
  TBranch *b_JetPt_;
  mutable bool c_JetPt_;
  std::vector<double>  MaxE2E10_;
  std::vector<double>  *p_MaxE2E10_;
  TBranch *b_MaxE2E10_;
  mutable bool c_MaxE2E10_;
  std::vector<double>  MinE2E10_;
  std::vector<double>  *p_MinE2E10_;
  TBranch *b_MinE2E10_;
  mutable bool c_MinE2E10_;
  std::vector<double>  MuonCalEnergyEm_;
  std::vector<double>  *p_MuonCalEnergyEm_;
  TBranch *b_MuonCalEnergyEm_;
  mutable bool c_MuonCalEnergyEm_;
  std::vector<double>  MuonCalEnergyEmS25_;
  std::vector<double>  *p_MuonCalEnergyEmS25_;
  TBranch *b_MuonCalEnergyEmS25_;
  mutable bool c_MuonCalEnergyEmS25_;
  std::vector<double>  MuonCalEnergyHad_;
  std::vector<double>  *p_MuonCalEnergyHad_;
  TBranch *b_MuonCalEnergyHad_;
  mutable bool c_MuonCalEnergyHad_;
  std::vector<double>  MuonCalEnergyHadS9_;
  std::vector<double>  *p_MuonCalEnergyHadS9_;
  TBranch *b_MuonCalEnergyHadS9_;
  mutable bool c_MuonCalEnergyHadS9_;
  std::vector<double>  MuonEta_;
  std::vector<double>  *p_MuonEta_;
  TBranch *b_MuonEta_;
  mutable bool c_MuonEta_;
  std::vector<double>  MuonPhi_;
  std::vector<double>  *p_MuonPhi_;
  TBranch *b_MuonPhi_;
  mutable bool c_MuonPhi_;
  std::vector<double>  MuonPt_;
  std::vector<double>  *p_MuonPt_;
  TBranch *b_MuonPt_;
  mutable bool c_MuonPt_;
  std::vector<double>  NegativeNoiseSumE_;
  std::vector<double>  *p_NegativeNoiseSumE_;
  TBranch *b_NegativeNoiseSumE_;
  mutable bool c_NegativeNoiseSumE_;
  std::vector<double>  NegativeNoiseSumEt_;
  std::vector<double>  *p_NegativeNoiseSumEt_;
  TBranch *b_NegativeNoiseSumEt_;
  mutable bool c_NegativeNoiseSumEt_;
  std::vector<double>  NominalMET_;
  std::vector<double>  *p_NominalMET_;
  TBranch *b_NominalMET_;
  mutable bool c_NominalMET_;
  std::vector<double>  RBXEnergy_;
  std::vector<double>  *p_RBXEnergy_;
  TBranch *b_RBXEnergy_;
  mutable bool c_RBXEnergy_;
  std::vector<double>  RBXEnergy15_;
  std::vector<double>  *p_RBXEnergy15_;
  TBranch *b_RBXEnergy15_;
  mutable bool c_RBXEnergy15_;
  std::vector<double>  SpikeNoiseSumE_;
  std::vector<double>  *p_SpikeNoiseSumE_;
  TBranch *b_SpikeNoiseSumE_;
  mutable bool c_SpikeNoiseSumE_;
  std::vector<double>  SpikeNoiseSumEt_;
  std::vector<double>  *p_SpikeNoiseSumEt_;
  TBranch *b_SpikeNoiseSumEt_;
  mutable bool c_SpikeNoiseSumEt_;
  std::vector<float>  HBHERecHitEnergy_;
  std::vector<float>  *p_HBHERecHitEnergy_;
  TBranch *b_HBHERecHitEnergy_;
  mutable bool c_HBHERecHitEnergy_;
  std::vector<float>  HBHERecHitEta_;
  std::vector<float>  *p_HBHERecHitEta_;
  TBranch *b_HBHERecHitEta_;
  mutable bool c_HBHERecHitEta_;
  std::vector<float>  HBHERecHitPhi_;
  std::vector<float>  *p_HBHERecHitPhi_;
  TBranch *b_HBHERecHitPhi_;
  mutable bool c_HBHERecHitPhi_;
  std::vector<float>  HBHERecHitTime_;
  std::vector<float>  *p_HBHERecHitTime_;
  TBranch *b_HBHERecHitTime_;
  mutable bool c_HBHERecHitTime_;
  std::vector<float>  HFRecHitEnergy_;
  std::vector<float>  *p_HFRecHitEnergy_;
  TBranch *b_HFRecHitEnergy_;
  mutable bool c_HFRecHitEnergy_;
  std::vector<float>  HFRecHitEta_;
  std::vector<float>  *p_HFRecHitEta_;
  TBranch *b_HFRecHitEta_;
  mutable bool c_HFRecHitEta_;
  std::vector<float>  HFRecHitPhi_;
  std::vector<float>  *p_HFRecHitPhi_;
  TBranch *b_HFRecHitPhi_;
  mutable bool c_HFRecHitPhi_;
  std::vector<float>  HFRecHitTime_;
  std::vector<float>  *p_HFRecHitTime_;
  TBranch *b_HFRecHitTime_;
  mutable bool c_HFRecHitTime_;
  std::vector<int>  HBHEDigiDepth_;
  std::vector<int>  *p_HBHEDigiDepth_;
  TBranch *b_HBHEDigiDepth_;
  mutable bool c_HBHEDigiDepth_;
  std::vector<int>  HBHEDigiIEta_;
  std::vector<int>  *p_HBHEDigiIEta_;
  TBranch *b_HBHEDigiIEta_;
  mutable bool c_HBHEDigiIEta_;
  std::vector<int>  HBHEDigiIPhi_;
  std::vector<int>  *p_HBHEDigiIPhi_;
  TBranch *b_HBHEDigiIPhi_;
  mutable bool c_HBHEDigiIPhi_;
  std::vector<int>  HBHERecHitAux_;
  std::vector<int>  *p_HBHERecHitAux_;
  TBranch *b_HBHERecHitAux_;
  mutable bool c_HBHERecHitAux_;
  std::vector<int>  HBHERecHitDepth_;
  std::vector<int>  *p_HBHERecHitDepth_;
  TBranch *b_HBHERecHitDepth_;
  mutable bool c_HBHERecHitDepth_;
  std::vector<int>  HBHERecHitFlags_;
  std::vector<int>  *p_HBHERecHitFlags_;
  TBranch *b_HBHERecHitFlags_;
  mutable bool c_HBHERecHitFlags_;
  std::vector<int>  HBHERecHitHPDid_;
  std::vector<int>  *p_HBHERecHitHPDid_;
  TBranch *b_HBHERecHitHPDid_;
  mutable bool c_HBHERecHitHPDid_;
  std::vector<int>  HBHERecHitIEta_;
  std::vector<int>  *p_HBHERecHitIEta_;
  TBranch *b_HBHERecHitIEta_;
  mutable bool c_HBHERecHitIEta_;
  std::vector<int>  HBHERecHitIPhi_;
  std::vector<int>  *p_HBHERecHitIPhi_;
  TBranch *b_HBHERecHitIPhi_;
  mutable bool c_HBHERecHitIPhi_;
  std::vector<int>  HBHERecHitRBXid_;
  std::vector<int>  *p_HBHERecHitRBXid_;
  TBranch *b_HBHERecHitRBXid_;
  mutable bool c_HBHERecHitRBXid_;
  std::vector<int>  HBHERecHitSevLvl_;
  std::vector<int>  *p_HBHERecHitSevLvl_;
  TBranch *b_HBHERecHitSevLvl_;
  mutable bool c_HBHERecHitSevLvl_;
  std::vector<int>  HFPhase1RecHitDepth_;
  std::vector<int>  *p_HFPhase1RecHitDepth_;
  TBranch *b_HFPhase1RecHitDepth_;
  mutable bool c_HFPhase1RecHitDepth_;
  std::vector<int>  HFPhase1RecHitIEta_;
  std::vector<int>  *p_HFPhase1RecHitIEta_;
  TBranch *b_HFPhase1RecHitIEta_;
  mutable bool c_HFPhase1RecHitIEta_;
  std::vector<int>  HFPhase1RecHitIPhi_;
  std::vector<int>  *p_HFPhase1RecHitIPhi_;
  TBranch *b_HFPhase1RecHitIPhi_;
  mutable bool c_HFPhase1RecHitIPhi_;
  std::vector<int>  HFRecHitAux_;
  std::vector<int>  *p_HFRecHitAux_;
  TBranch *b_HFRecHitAux_;
  mutable bool c_HFRecHitAux_;
  std::vector<int>  HFRecHitDepth_;
  std::vector<int>  *p_HFRecHitDepth_;
  TBranch *b_HFRecHitDepth_;
  mutable bool c_HFRecHitDepth_;
  std::vector<int>  HFRecHitFlags_;
  std::vector<int>  *p_HFRecHitFlags_;
  TBranch *b_HFRecHitFlags_;
  mutable bool c_HFRecHitFlags_;
  std::vector<int>  HFRecHitHPDid_;
  std::vector<int>  *p_HFRecHitHPDid_;
  TBranch *b_HFRecHitHPDid_;
  mutable bool c_HFRecHitHPDid_;
  std::vector<int>  HFRecHitIEta_;
  std::vector<int>  *p_HFRecHitIEta_;
  TBranch *b_HFRecHitIEta_;
  mutable bool c_HFRecHitIEta_;
  std::vector<int>  HFRecHitIPhi_;
  std::vector<int>  *p_HFRecHitIPhi_;
  TBranch *b_HFRecHitIPhi_;
  mutable bool c_HFRecHitIPhi_;
  std::vector<int>  HFRecHitRBXid_;
  std::vector<int>  *p_HFRecHitRBXid_;
  TBranch *b_HFRecHitRBXid_;
  mutable bool c_HFRecHitRBXid_;
  std::vector<int>  HLTBits_;
  std::vector<int>  *p_HLTBits_;
  TBranch *b_HLTBits_;
  mutable bool c_HLTBits_;
  std::vector<int>  HLTInsideDatasetTriggerPrescales_;
  std::vector<int>  *p_HLTInsideDatasetTriggerPrescales_;
  TBranch *b_HLTInsideDatasetTriggerPrescales_;
  mutable bool c_HLTInsideDatasetTriggerPrescales_;
  std::vector<int>  HLTOutsideDatasetTriggerPrescales_;
  std::vector<int>  *p_HLTOutsideDatasetTriggerPrescales_;
  TBranch *b_HLTOutsideDatasetTriggerPrescales_;
  mutable bool c_HLTOutsideDatasetTriggerPrescales_;
  std::vector<int>  HPDHits_;
  std::vector<int>  *p_HPDHits_;
  TBranch *b_HPDHits_;
  mutable bool c_HPDHits_;
  std::vector<int>  HPDNoOtherHits_;
  std::vector<int>  *p_HPDNoOtherHits_;
  TBranch *b_HPDNoOtherHits_;
  mutable bool c_HPDNoOtherHits_;
  std::vector<int>  HasBadRBXR45_;
  std::vector<int>  *p_HasBadRBXR45_;
  TBranch *b_HasBadRBXR45_;
  mutable bool c_HasBadRBXR45_;
  std::vector<int>  HasBadRBXRechitR45Loose_;
  std::vector<int>  *p_HasBadRBXRechitR45Loose_;
  TBranch *b_HasBadRBXRechitR45Loose_;
  mutable bool c_HasBadRBXRechitR45Loose_;
  std::vector<int>  HasBadRBXRechitR45Tight_;
  std::vector<int>  *p_HasBadRBXRechitR45Tight_;
  TBranch *b_HasBadRBXRechitR45Tight_;
  mutable bool c_HasBadRBXRechitR45Tight_;
  std::vector<int>  IsoNoiseFilterDecision_;
  std::vector<int>  *p_IsoNoiseFilterDecision_;
  TBranch *b_IsoNoiseFilterDecision_;
  mutable bool c_IsoNoiseFilterDecision_;
  std::vector<int>  JetN60_;
  std::vector<int>  *p_JetN60_;
  TBranch *b_JetN60_;
  mutable bool c_JetN60_;
  std::vector<int>  JetN90_;
  std::vector<int>  *p_JetN90_;
  TBranch *b_JetN90_;
  mutable bool c_JetN90_;
  std::vector<int>  MaxZeros_;
  std::vector<int>  *p_MaxZeros_;
  TBranch *b_MaxZeros_;
  mutable bool c_MaxZeros_;
  std::vector<int>  MuonCSC2DRecHitsSize_;
  std::vector<int>  *p_MuonCSC2DRecHitsSize_;
  TBranch *b_MuonCSC2DRecHitsSize_;
  mutable bool c_MuonCSC2DRecHitsSize_;
  std::vector<int>  MuonCSCSegmentsSize_;
  std::vector<int>  *p_MuonCSCSegmentsSize_;
  TBranch *b_MuonCSCSegmentsSize_;
  mutable bool c_MuonCSCSegmentsSize_;
  std::vector<int>  MuonDT1DCosmicRecHitsSize_;
  std::vector<int>  *p_MuonDT1DCosmicRecHitsSize_;
  TBranch *b_MuonDT1DCosmicRecHitsSize_;
  mutable bool c_MuonDT1DCosmicRecHitsSize_;
  std::vector<int>  MuonDT1DRecHitsSize_;
  std::vector<int>  *p_MuonDT1DRecHitsSize_;
  TBranch *b_MuonDT1DRecHitsSize_;
  mutable bool c_MuonDT1DRecHitsSize_;
  std::vector<int>  MuonDTRecCosmicSegmentsSize_;
  std::vector<int>  *p_MuonDTRecCosmicSegmentsSize_;
  TBranch *b_MuonDTRecCosmicSegmentsSize_;
  mutable bool c_MuonDTRecCosmicSegmentsSize_;
  std::vector<int>  MuonDTRecSegmentsSize_;
  std::vector<int>  *p_MuonDTRecSegmentsSize_;
  TBranch *b_MuonDTRecSegmentsSize_;
  mutable bool c_MuonDTRecSegmentsSize_;
  std::vector<int>  MuonNumberOfChambers_;
  std::vector<int>  *p_MuonNumberOfChambers_;
  TBranch *b_MuonNumberOfChambers_;
  mutable bool c_MuonNumberOfChambers_;
  std::vector<int>  MuonNumberOfMatchedRPCLayers_;
  std::vector<int>  *p_MuonNumberOfMatchedRPCLayers_;
  TBranch *b_MuonNumberOfMatchedRPCLayers_;
  mutable bool c_MuonNumberOfMatchedRPCLayers_;
  std::vector<int>  MuonNumberOfMatchedStations_;
  std::vector<int>  *p_MuonNumberOfMatchedStations_;
  TBranch *b_MuonNumberOfMatchedStations_;
  mutable bool c_MuonNumberOfMatchedStations_;
  std::vector<int>  MuonRPCRecHitsSize_;
  std::vector<int>  *p_MuonRPCRecHitsSize_;
  TBranch *b_MuonRPCRecHitsSize_;
  mutable bool c_MuonRPCRecHitsSize_;
  std::vector<int>  NumIsolatedNoiseChannels_;
  std::vector<int>  *p_NumIsolatedNoiseChannels_;
  TBranch *b_NumIsolatedNoiseChannels_;
  mutable bool c_NumIsolatedNoiseChannels_;
  std::vector<int>  NumNegativeNoiseChannels_;
  std::vector<int>  *p_NumNegativeNoiseChannels_;
  TBranch *b_NumNegativeNoiseChannels_;
  mutable bool c_NumNegativeNoiseChannels_;
  std::vector<int>  NumSpikeNoiseChannels_;
  std::vector<int>  *p_NumSpikeNoiseChannels_;
  TBranch *b_NumSpikeNoiseChannels_;
  mutable bool c_NumSpikeNoiseChannels_;
  std::vector<int>  Nvtx_;
  std::vector<int>  *p_Nvtx_;
  TBranch *b_Nvtx_;
  mutable bool c_Nvtx_;
  std::vector<int>  OfficialDecision_;
  std::vector<int>  *p_OfficialDecision_;
  TBranch *b_OfficialDecision_;
  mutable bool c_OfficialDecision_;
  std::vector<int>  OfficialDecisionRun1_;
  std::vector<int>  *p_OfficialDecisionRun1_;
  TBranch *b_OfficialDecisionRun1_;
  mutable bool c_OfficialDecisionRun1_;
  std::vector<int>  OfficialDecisionRun2L_;
  std::vector<int>  *p_OfficialDecisionRun2L_;
  TBranch *b_OfficialDecisionRun2L_;
  mutable bool c_OfficialDecisionRun2L_;
  std::vector<int>  OfficialDecisionRun2T_;
  std::vector<int>  *p_OfficialDecisionRun2T_;
  TBranch *b_OfficialDecisionRun2T_;
  mutable bool c_OfficialDecisionRun2T_;
  std::vector<int>  QIE10DigiDepth_;
  std::vector<int>  *p_QIE10DigiDepth_;
  TBranch *b_QIE10DigiDepth_;
  mutable bool c_QIE10DigiDepth_;
  std::vector<int>  QIE10DigiIEta_;
  std::vector<int>  *p_QIE10DigiIEta_;
  TBranch *b_QIE10DigiIEta_;
  mutable bool c_QIE10DigiIEta_;
  std::vector<int>  QIE10DigiIPhi_;
  std::vector<int>  *p_QIE10DigiIPhi_;
  TBranch *b_QIE10DigiIPhi_;
  mutable bool c_QIE10DigiIPhi_;
  std::vector<int>  QIE11DigiDepth_;
  std::vector<int>  *p_QIE11DigiDepth_;
  TBranch *b_QIE11DigiDepth_;
  mutable bool c_QIE11DigiDepth_;
  std::vector<int>  QIE11DigiIEta_;
  std::vector<int>  *p_QIE11DigiIEta_;
  TBranch *b_QIE11DigiIEta_;
  mutable bool c_QIE11DigiIEta_;
  std::vector<int>  QIE11DigiIPhi_;
  std::vector<int>  *p_QIE11DigiIPhi_;
  TBranch *b_QIE11DigiIPhi_;
  mutable bool c_QIE11DigiIPhi_;
  std::vector<std::string>  HLTInsideDatasetTriggerNames_;
  std::vector<std::string>  *p_HLTInsideDatasetTriggerNames_;
  TBranch *b_HLTInsideDatasetTriggerNames_;
  mutable bool c_HLTInsideDatasetTriggerNames_;
  std::vector<std::string>  HLTOutsideDatasetTriggerNames_;
  std::vector<std::string>  *p_HLTOutsideDatasetTriggerNames_;
  TBranch *b_HLTOutsideDatasetTriggerNames_;
  mutable bool c_HLTOutsideDatasetTriggerNames_;
  std::vector<std::vector<double> >  HBHERecHitAuxAllfC_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxAllfC_;
  TBranch *b_HBHERecHitAuxAllfC_;
  mutable bool c_HBHERecHitAuxAllfC_;
  std::vector<std::vector<double> >  HBHERecHitAuxEnergy_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxEnergy_;
  TBranch *b_HBHERecHitAuxEnergy_;
  mutable bool c_HBHERecHitAuxEnergy_;
  std::vector<std::vector<double> >  HBHERecHitAuxFC_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxFC_;
  TBranch *b_HBHERecHitAuxFC_;
  mutable bool c_HBHERecHitAuxFC_;
  std::vector<std::vector<double> >  HBHERecHitAuxGain_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxGain_;
  TBranch *b_HBHERecHitAuxGain_;
  mutable bool c_HBHERecHitAuxGain_;
  std::vector<std::vector<double> >  HBHERecHitAuxPedFC_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxPedFC_;
  TBranch *b_HBHERecHitAuxPedFC_;
  mutable bool c_HBHERecHitAuxPedFC_;
  std::vector<std::vector<double> >  HBHERecHitAuxRCGain_;
  std::vector<std::vector<double> >  *p_HBHERecHitAuxRCGain_;
  TBranch *b_HBHERecHitAuxRCGain_;
  mutable bool c_HBHERecHitAuxRCGain_;
  std::vector<std::vector<double> >  QIE10DigiFC_;
  std::vector<std::vector<double> >  *p_QIE10DigiFC_;
  TBranch *b_QIE10DigiFC_;
  mutable bool c_QIE10DigiFC_;
  std::vector<std::vector<double> >  QIE11DigiFC_;
  std::vector<std::vector<double> >  *p_QIE11DigiFC_;
  TBranch *b_QIE11DigiFC_;
  mutable bool c_QIE11DigiFC_;
  std::vector<std::vector<double> >  RBXCharge_;
  std::vector<std::vector<double> >  *p_RBXCharge_;
  TBranch *b_RBXCharge_;
  mutable bool c_RBXCharge_;
  std::vector<std::vector<double> >  RBXCharge15_;
  std::vector<std::vector<double> >  *p_RBXCharge15_;
  TBranch *b_RBXCharge15_;
  mutable bool c_RBXCharge15_;
  std::vector<std::vector<float> >  HBHEDigiAllFC_;
  std::vector<std::vector<float> >  *p_HBHEDigiAllFC_;
  TBranch *b_HBHEDigiAllFC_;
  mutable bool c_HBHEDigiAllFC_;
  std::vector<std::vector<float> >  HFPhase1RecHitQie10Charge_;
  std::vector<std::vector<float> >  *p_HFPhase1RecHitQie10Charge_;
  TBranch *b_HFPhase1RecHitQie10Charge_;
  mutable bool c_HFPhase1RecHitQie10Charge_;
  std::vector<std::vector<float> >  HFPhase1RecHitQie10Energy_;
  std::vector<std::vector<float> >  *p_HFPhase1RecHitQie10Energy_;
  TBranch *b_HFPhase1RecHitQie10Energy_;
  mutable bool c_HFPhase1RecHitQie10Energy_;
  std::vector<std::vector<float> >  HFPhase1RecHitQie10Time_;
  std::vector<std::vector<float> >  *p_HFPhase1RecHitQie10Time_;
  TBranch *b_HFPhase1RecHitQie10Time_;
  mutable bool c_HFPhase1RecHitQie10Time_;
  std::vector<std::vector<int> >  HBHERecHitAuxADC_;
  std::vector<std::vector<int> >  *p_HBHERecHitAuxADC_;
  TBranch *b_HBHERecHitAuxADC_;
  mutable bool c_HBHERecHitAuxADC_;
  std::vector<std::vector<int> >  HBHERecHitAuxCapID_;
  std::vector<std::vector<int> >  *p_HBHERecHitAuxCapID_;
  TBranch *b_HBHERecHitAuxCapID_;
  mutable bool c_HBHERecHitAuxCapID_;
  std::vector<std::vector<int> >  L1PhysBits_;
  std::vector<std::vector<int> >  *p_L1PhysBits_;
  TBranch *b_L1PhysBits_;
  mutable bool c_L1PhysBits_;
  std::vector<std::vector<int> >  L1TechBits_;
  std::vector<std::vector<int> >  *p_L1TechBits_;
  TBranch *b_L1TechBits_;
  mutable bool c_L1TechBits_;
  std::vector<std::vector<int> >  QIE10DigiLETDC_;
  std::vector<std::vector<int> >  *p_QIE10DigiLETDC_;
  TBranch *b_QIE10DigiLETDC_;
  mutable bool c_QIE10DigiLETDC_;
};

hcal_tree* NewTree(const std::type_info &type);

#include "hcal_tree_noise.hpp"

#endif
